@startuml
web->web:平台审核通过
web->供票服务:平台审核通过
供票服务->工作流:修改当前任务节点（出票登记(issueRegisterAudit)）
工作流-->供票服务:修改结果
供票服务->票交所:发送票据信息（mq）
供票服务-->web:结果
== 回调通知 ==
...
票交所-->供票服务:mq结果通知
供票服务->供票服务:校验消息结果
alt 成功
activate 供票服务
供票服务->供票服务:创建bill记录（bill表）
供票服务->供票服务:修改trade表状态，2-待审核->4-关闭
供票服务->供票服务:回填trade_detail表信息（pjs_range_start，pjs_range_end）
供票服务->供票服务:修改assert表状态， 0:初始->1:正常
供票服务->工作流:结果当前任务流程
工作流-->供票服务:修改结果
供票服务->短信服务:发送通知短信
deactivate
else 失败

供票服务->供票服务:修改当前任务节点（平台审批(platformAudit)）
activate 供票服务
供票服务->短信服务:发送通知短信
deactivate
end

@enduml